# Generated by Django 5.0.6 on 2024-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designasset',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='designasset',
            name='tags',
            field=models.TextField(blank=True, default=list),
        ),
    ]
