# Generated by Django 5.0.6 on 2024-12-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_panel", "0002_designasset_size_designasset_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="yearbook",
        ),
        migrations.RemoveField(
            model_name="yearbook",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Yearbook",
        ),
    ]
