# Generated by Django 5.0.6 on 2024-12-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_customuser_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="permissions",
        ),
    ]
