# Generated by Django 5.0.6 on 2024-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_remove_customuser_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
