# Generated by Django 5.0.6 on 2025-02-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_customuser_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='permissions',
        ),
    ]
