# Generated by Django 5.0.6 on 2024-10-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pdffile_remove_cart_quantity_amount_cart_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='pages',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
