# Generated by Django 5.0.6 on 2024-12-03 15:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_editedpdftemplate_imageurl_editedpdftemplate_pdftype_and_more'),
        ('login', '0002_customuser_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editedpdftemplate',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='editedpdftemplate',
            old_name='pdfType',
            new_name='pdf_type',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='allyearbooks',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='allyearbooks',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.customuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='sessionlink',
            name='pdf_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='yearbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='accounts.temporaryyearbooks'),
        ),
        migrations.AlterField(
            model_name='sessionlink',
            name='link',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_link', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_access', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='login.customuser')),
            ],
            options={
                'unique_together': {('user', 'permission_link')},
            },
        ),
    ]
