# Generated by Django 5.0.6 on 2024-12-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_imageurl_editedpdftemplate_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_details',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ip_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_account_balance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_approval_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_avs_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_avs_response',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_avs_zip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_card_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_card_short_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_card_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_cvv2_response',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_exp_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_invoice_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_issuer_response',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_merchant_initiated_unscheduled',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_oar_data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_par_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_partner_app_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_ps2000_data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_result',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_result_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_token_response',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_transaction_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_txn_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ssl_txn_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
