# Generated by Django 5.0.6 on 2024-12-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_payment_amount_remove_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='yearbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.allyearbooks'),
        ),
    ]
